namespace Core.Application.Services;

/// <summary>
/// Represents a token generated by a <see cref="ITokenService"> implementation.
/// </summary>
public readonly struct TokenInfo
{
    /// <summary>
    /// Gets the actual token data.
    /// </summary>
    public readonly string Token { get; init; }

    /// <summary>
    /// Gets the token creation date.
    /// </summary>
    public readonly DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// Gets the token expiration date.
    /// </summary>
    public readonly DateTimeOffset ExpiresAt { get; init; }
}

/// <summary>
/// Represents an abstraction for generating access & refresh tokens.
/// </summary>
public interface ITokenService
{
    /// <summary>
    /// Generates a new access token using provided user information.
    /// </summary>
    public TokenInfo GenerateAccessToken(string identity, string username, string email, params ReadOnlySpan<string> roles);

    /// <summary>
    /// Generates a new refresh token.
    /// </summary>
    public TokenInfo GenerateRefreshToken();
}
